name: healthapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_database: ^10.5.2
  cloud_firestore: ^4.17.0
  firebase_core_platform_interface: ^5.0.0
  fl_chart: ^0.67.0
  syncfusion_flutter_charts: ^25.1.39+1

  sqflite: ^2.3.0
  path: any

  cupertino_icons: ^1.0.2
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  assets:
    - assets/databases/nutrition.db

  uses-material-design: true
