name: healthapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.24.0
  firebase_database: ^9.0.16
  firebase_core_platform_interface: 4.5.1
  cloud_firestore: any
  fl_chart: ^0.67.0

  sqflite: ^2.3.0
  path: any

  cupertino_icons: ^1.0.2
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/databases/nutrition.db

  uses-material-design: true
