name: healthapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.29.0
  cloud_firestore: ^4.15.8
  firebase_core_platform_interface: ^5.0.0

  fl_chart: ^0.67.0
  tuple: ^2.0.2
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true
