// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDJS842TxZqBCLMVbhhBwGnl-Iccgqulc',
    appId: '1:887939656540:web:bf872568edc116b7162f99',
    messagingSenderId: '887939656540',
    projectId: 'nutritionapp-b2fe8',
    authDomain: 'nutritionapp-b2fe8.firebaseapp.com',
    storageBucket: 'nutritionapp-b2fe8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyGdTQa-AhkRgehD-uSSPbGc644r6cVaY',
    appId: '1:887939656540:android:8c2c447f09d12497162f99',
    messagingSenderId: '887939656540',
    projectId: 'nutritionapp-b2fe8',
    storageBucket: 'nutritionapp-b2fe8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDJS842TxZqBCLMVbhhBwGnl-Iccgqulc',
    appId: '1:887939656540:web:34baa0ce9f60800d162f99',
    messagingSenderId: '887939656540',
    projectId: 'nutritionapp-b2fe8',
    authDomain: 'nutritionapp-b2fe8.firebaseapp.com',
    storageBucket: 'nutritionapp-b2fe8.appspot.com',
  );
}
